Load in numpy (remember to conda install numpy first)

In [605]:
import numpy as np

The Basics

In [606]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [560]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [561]:
# Get Dimension
a.ndim

1

In [562]:
# Get shape
b.shape

(2, 3)

In [563]:
# Get type
a.dtype

dtype('int64')

In [564]:
# Get size (in bytes)
b.itemsize 
# returns the size (in bytes) of each element in the array

8

In [565]:
# Get size
b.size 
# returns the total number of elements in the array

6

In [566]:
# Get total size
#b.itemsize * b.size = b. nbytes
b.nbytes

48

Accessing/Changing specific elements, rows, columns, etc

In [567]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [568]:
# Get a specific element [r, c]
# To get 9
a[1, 1]
# To get 13
# a[1, 5]

9

In [569]:
# Get a specific rows
# To get row1
a[0, :]
# To get row2
# a[1, :]

array([1, 2, 3, 4, 5, 6, 7])

In [570]:
# Get a specific columns
# To get column1
a[:, 0]
# To get column5
# a[:, 4]

array([1, 8])

In [571]:
# Getting a little more fancy (startndex/endindex/stepsize)
# To get [2, 4, 6]
a[0, 1:6:2] # a[0, 1:-1:2]

array([2, 4, 6])

In [572]:
# Changing number
a[1,5] = 20
print(a)
a[:, 3] = [2,4]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  3  2  5  6  7]
 [ 8  9 10  4 12 20 14]]


3D array example

In [573]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [574]:
# Get a specific element [r, c]
# To get 4
b[0, 1, 1]
# To get 6
# b[1, 0, 1]

4

In [575]:
# replace
b[:, 1, :] = [[9, 9], [10, 10]]
print(b)

[[[ 1  2]
  [ 9  9]]

 [[ 5  6]
  [10 10]]]


Initializing Different Types of Arrays

In [576]:
# All 0s matrix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [577]:
# All 1s matrix
np.ones((2,2,2), dtype = "int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [578]:
# Any other number
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

In [579]:
# Any other number (full_like)
a = np.array([[1, 2, 3], [4, 5, 6]])
np.full_like(a, 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [580]:
# Random decimal numbers
np.random.rand(2, 3)

array([[0.39888948, 0.89431879, 0.76964194],
       [0.3312893 , 0.94612121, 0.17434159]])

In [581]:
# Random decimal numbers
# To copy from a
a = np.array([[1, 2, 3], [4, 5, 6]])
np.random.random_sample(a.shape)

array([[0.85752288, 0.73386917, 0.95155668],
       [0.32188544, 0.18358207, 0.45695805]])

In [582]:
# Random integer values
np.random.randint(-5,5, size = (2, 3))

array([[ 4,  2, -1],
       [ 0, -2, -3]])

In [583]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [584]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)
r2 = np.repeat(arr, 3, axis = 1)
print(r2)
# axis = 0 : along Rows
# axis = 1 : along Columns

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [585]:
# practice
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [586]:
# Be careful when coping arrays
a = np.array([1, 2, 3])
b = a.copy() # .copy() a不會改變 
b[0] = 100
print(b)

[100   2   3]


Mathematics

In [587]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [588]:
a + 2

array([3, 4, 5, 6])

In [589]:
a - 2

array([-1,  0,  1,  2])

In [590]:
a * 2

array([2, 4, 6, 8])

In [591]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [592]:
a ** 2

array([ 1,  4,  9, 16])

In [593]:
b = np.array([1, 0, 1, 0])
b + a

array([2, 2, 4, 4])

In [594]:
# Take the sin/cos
np.sin(a) # np.cos(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Linear Algebra

In [595]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [596]:
# Find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

Statistics

In [597]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [598]:
np.min(stats)

1

In [599]:
np.max(stats, axis = 1)

array([3, 6])

In [600]:
np.sum(stats)

21

Reorganizing Arrays

In [601]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [602]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [603]:
# Horizontal stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Miscellaneous

In [604]:
# Load data from File
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata = filedata.astype('int32')
print(filedata)

FileNotFoundError: data.txt not found.

In [ ]:
# Boolean Masking and Advanced Indexing
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [ ]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
(filedata > 50) & (filedata < 100) 
# (~((filedata > 50) & (filedata < 100))) # 相反

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])